---
- name: Install reflector
  ansible.builtin.package:
    name: reflector
    state: present
  become: yes

- name: Configure reflector service
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: /etc/xdg/reflector/reflector.conf
    mode: preserve
    force: yes
    validate: /usr/bin/reflector @%s --save /dev/null
  become: yes
  notify: Regenerate package list

- name: Enable reflector systemd timer
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
    enabled: yes
  become: yes
