---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
    role-file: molecule/default/requirements.yml
lint: |
  set -e
  yamllint --strict ./
  ansible-lint
driver:
  name: ${MOL_DRIVER:-podman}
platforms:
  - name: mol-reflector-arch
    image: gliech/docker-archlinux-ansible:latest
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  check_sequence:
    - dependency
    - create
    - prepare
    - converge
    - check
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
