---
on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pdm
        uses: pdm-project/setup-pdm@v2

      - name: Full molecule test
        run: |
          pdm install --no-self
          pdm run molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOL_DRIVER: docker
  release:
    name: release new version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Create new release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          extra_plugins: "@gliech/semantic-release-generic-github-config"
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
