---
on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: reflector
    env:
      PIPENV_DOTENV_LOCATION: .github/ci.env
      PY_COLORS: "1"
      ANSIBLE_FORCE_COLOR: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: reflector

      - name: Restore pipenv cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pipenv
          key: pipenv-${{ hashFiles('reflector/Pipfile.lock') }}
          restore-keys: pipenv-

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev

      - name: Full molecule test
        run: pipenv run molecule test
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Create new release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          extra_plugins: "@gliech/semantic-release-generic-github-config"
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
